[package]
org = "israel_shingenge"
name = "Logistics_S"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "kafka"
version = "3.8.0"

[[platform.java11.dependency]]
path= "C:\\Users\\Israel Shingenge\\Documents\\Jars\\mysql-connector-j-9.0.0\\mysql-connector-j-9.0.0\\mysql-connector-j-9.0.0\\mysql-connector-j-9.0.0.jar"